version: 2

sources:
  - name: jaffle_shop
    database: "{{target.database}}"
    schema: "{{target.schema}}"
    tables:
      - name: customers
      - name: orders
        loaded_at_field: '"ORDER_DATE"::timestamp'
        freshness:
          warn_after: {count: 12, period: hour}
          error_after: {count: 24, period: hour}
        columns:
          - name: order_date
            tests:
              - dbt_utils.not_empty_string:
                  trim_whitespace: true # Optional
                  config:
                    tags:
                      - blabla
                  meta:
                    owner:
                      - ofek@elementary-data.com
  - name: stripe
    database: "{{target.database}}"
    schema: "{{target.schema}}"
    tables:
      - name: payment
        loaded_at_field: '"ORDER_DATE"'
        freshness:
          warn_after: {count: 12, period: hour}
          error_after: {count: 24, period: hour}
