version: 2

sources:
  - name: jaffle_shop
    database: "{{target.database}}"
    schema: "{{target.schema}}"
    tables:
      - name: customers
      - name: orders
        loaded_at_field: _etl_loaded_at
        freshness:
          warn_after: {count: 12, period: hour}
          error_after: {count: 24, period: hour}
  - name: stripe
    database: "{{target.database}}"
    schema: "{{target.schema}}"
    tables:
      - name: payment
        loaded_at_field: _batched_at
        freshness:
          warn_after: {count: 12, period: hour}
          error_after: {count: 24, period: hour}