version: 2

sources:
  - name: jaffle_shop
    database: "{{target.database or target.schema}}"
    schema: "{{target.schema}}"
    tables:
      - name: customers
      - name: orders
        loaded_at_field: '"ORDER_DATE"::timestamp'
        freshness:
          warn_after: {count: 12, period: hour}
          error_after: {count: 24, period: hour}
  - name: stripe
    database: "{{target.database or target.schema}}"
    schema: "{{target.schema}}"
    tables:
      - name: payment
        loaded_at_field: '"ORDER_DATE"'
        freshness:
          warn_after: {count: 12, period: hour}
          error_after: {count: 24, period: hour}
  - name: all_dates
    database: "{{target.database or target.schema}}"
    schema: "{{target.schema}}"
    tables:
      - name: all_dates
        loaded_at_field: '"date_day"'
        freshness:
          warn_after: {count: 72, period: hour}
          error_after: {count: 100, period: hour}